JAVA/roman-to-integer.java
Roman to Integer Leetcode solution => https://leetcode.com/problems/roman-to-integer/
=> Adding solution of leetcode question

JAVA/Anagaram_with_substring.java, JAVA/Reversing_Sentence_Without reversing_word.java, JAVA/prime_add.java, JAVA/subset_array.java
=> Added Anagram prime reverse and subset programs

Algorithms/BubbleSort.java, Algorithms/BucketSort.java, Algorithms/CycleSort.java, Algorithms/HeapSort.java, Algorithms/InsertionSort.java, Algorithms/MergeSort.java, Algorithms/QuickSort.java, Algorithms/RadixSort.java, Algorithms/SelectionSort.java, Algorithms/ShellSort.java, Algorithms/TreeSort.java
Please add my file to in your repository with label hacktoberfest
=> hacktoberfest-2022

Python/radixSort.py
=> [Python] Radix Sort

Python/countingSortString.py
Counting Sort for String value
=> [Python] Counting Sort for String value

Python/radixSort.py, Python/selectionSort.py
=> [Python] Selection Sort

Python/quickSort.py
=> [Python] Quick Sort

JAVA/bubbleSort.java
Bubble sort algorithm added in this repo. Kindly consider merging this PR.
=> Added bubble sort algorithm

Python/Factorial.py, Python/Palindrome.py
I have added two programs in python language.
1. Returns the factorial of a given number.
2. Checks if the given number is a palindrome or not.
=> factorial and palindrome functions added

JAVA/binarySearch.java
I have written a code for binary search through an array using recursion. Kindly consider merging my PR.
=> Binary Search using Recursion

Screen Pet with Python.py
hi there this is my second PR in this Hacktoberfest 2022 in this fest i have created Screen pet with python using tkinter.
=> Screen Pet with Python.py

JAVA/designPatterns/ThreadSafeSingleton.java
create a java design patterns - singleton pattern
=> add java design patterns - singleton pattern

Python/BubbleSort.py
Bubble Sort Algorithm in python
=> BubbleSort.py

JAVA/jobSequencing.java
added job sequencing problem solution in java
=> Added Job Sequencing

C++/Pattern
=> InterestingPattern

Python/sudoku_solver.py
A python based sudoku solver made using backtracking.
=> Added sudoku_solver.py

C++/INFIXPOST.cpp
Please add hacktoberfest 2022 tag to my PR as well. Thanks!!
=> Added Infix to Postfix in C++

JAVA/majelem.java
=> Majority Element usinh HashMap

C++/multiple inheritance.cpp
Hi! I added a Multiple inheritance program in C++ please accept my request
=> Multiple Inheritance Program in C++

JAVA/longestSubStr.java
please insert a hacktoberst2020 lable
=> add longestSubStr.java program
